### PR TITLE
merge upstream Gecko

### PR DESCRIPTION
**Pull request by mykmelez**
@brendandahl This branch updates SpiderWeb to the same upstream Gecko revision to which I just updated SpiderNode over in https://github.com/mozilla/spidernode/pull/214. There were a couple of IPC API changes to make, and I had to whitelist spiderweb/app for XPCOM glue, which is apparently no longer allowed (so we'll eventually have to figure out an alternative, or work around it by using Firefox's own process to run Node).

### CODE REVIEW

**Comment by mykmelez** [comment]
Note that this isn't yet building successfully for me yet. I'm seeing linker errors:

>Undefined symbols for architecture x86_64:
>  "__register_async_wrap", referenced from:
>      _main in Main.o
>  "__register_buffer", referenced from:
>      _main in Main.o
>  "__register_cares_wrap", referenced from:
>      _main in Main.o
>  "__register_config", referenced from:
>      _main in Main.o
>  "__register_contextify", referenced from:
>      _main in Main.o
>  "__register_crypto", referenced from:
>      _main in Main.o
>  "__register_fs", referenced from:
>      _main in Main.o
>  "__register_fs_event_wrap", referenced from:
>      _main in Main.o
>  "__register_http_parser", referenced from:
>      _main in Main.o
>  "__register_icu", referenced from:
>      _main in Main.o
>  "__register_js_stream", referenced from:
>      _main in Main.o
>  "__register_os", referenced from:
>      _main in Main.o
>  "__register_pipe_wrap", referenced from:
>      _main in Main.o
>  "__register_process_wrap", referenced from:
>      _main in Main.o
>  "__register_signal_wrap", referenced from:
>      _main in Main.o
>  "__register_spawn_sync", referenced from:
>      _main in Main.o
>  "__register_stream_wrap", referenced from:
>      _main in Main.o
>  "__register_tcp_wrap", referenced from:
>      _main in Main.o
>  "__register_timer_wrap", referenced from:
>      _main in Main.o
>  "__register_tls_wrap", referenced from:
>      _main in Main.o
>  "__register_tty_wrap", referenced from:
>      _main in Main.o
>  "__register_udp_wrap", referenced from:
>      _main in Main.o
>  "__register_util", referenced from:
>      _main in Main.o
>  "__register_uv", referenced from:
>      _main in Main.o
>  "__register_v8", referenced from:
>      _main in Main.o
>  "__register_zlib", referenced from:
>      _main in Main.o
>ld: symbol(s) not found for architecture x86_64
>clang: error: linker command failed with exit code 1 (use -v to see invocation

**Comment by mykmelez** [comment]
In order to avoid having to resolve those linker errors, I merged @brendandahl's #12, which gets rid of the separate executable that had those errors. This now builds correctly and runs successfully on my machine.

**Comment by brendandahl** [comment]
```
JavaScript error: resource://gre/modules/ExtensionCommon.jsm, line 390: Error: Not implemented
```

Looks like some upstream changes broke the node extension api's. In the addon child context the proxy to call `node.connect()` in the parent is not there (see ProxyAPIImplementation). Looks like we can only call a function with no returns or an async function. Still looking to see if there's an easy fix.

**Comment by brendandahl** [comment]
I have a workaround until that should be fine until web extensions are truly run in a different process. Will merge and fix.

**Pull request merged**
